"""
Database setup for VOXIA AI.

Local development defaults to SQLite. For deployment, set DATABASE_URL to
the Supabase PostgreSQL connection string. Prefer Supabase's Session pooler
connection string for serverless deployments and require SSL.

Supabase setup:
1. In Supabase Dashboard -> Database -> Extensions, enable the `vector`
   extension before deploying (VOXIA's RAG schema uses pgvector).
2. Set DATABASE_URL in the hosting provider's backend environment variables.
3. Deploy/restart the backend. SQLAlchemy creates missing tables on startup.
4. For an existing SQLite database, use migrate_sqlite_to_postgres.py.

EMBEDDING_DIM must match the vector length generated by rag.py (768 here).
"""

import math
import os
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker, declarative_base

DATABASE_URL = os.environ.get("DATABASE_URL", "sqlite:///./voxia.db").strip()

# Supabase gives a PostgreSQL URL. Normalize the legacy postgres:// form.
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = "postgresql://" + DATABASE_URL[len("postgres://"):]

# Require TLS for Supabase PostgreSQL unless the URL explicitly configures it.
if DATABASE_URL.startswith("postgresql://") and "sslmode=" not in DATABASE_URL:
    DATABASE_URL += ("&" if "?" in DATABASE_URL else "?") + "sslmode=require"

EMBEDDING_DIM = 768
VECTOR_INDEX_METHOD = os.environ.get("VECTOR_INDEX_METHOD", "hnsw").lower()

connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}
engine = create_engine(
    DATABASE_URL,
    connect_args=connect_args,
    pool_pre_ping=True,
)

IS_POSTGRES = engine.dialect.name == "postgresql"

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def ensure_pgvector_extension():
    """No-op on SQLite. Supabase users should enable vector in the dashboard."""
    if not IS_POSTGRES:
        return
    with engine.connect() as conn:
        conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))
        conn.commit()


def _table_row_count(conn, table_name: str) -> int:
    return conn.execute(text(f"SELECT count(*) FROM {table_name}")).scalar() or 0


def ensure_pgvector_indexes():
    """Create the optional pgvector ANN indexes after tables exist."""
    if not IS_POSTGRES or VECTOR_INDEX_METHOD == "none":
        return

    with engine.connect() as conn:
        for table in ("document_chunks", "memories"):
            index_name = f"ix_{table}_embedding_{VECTOR_INDEX_METHOD}"
            if VECTOR_INDEX_METHOD == "hnsw":
                conn.execute(
                    text(
                        f"CREATE INDEX IF NOT EXISTS {index_name} "
                        f"ON {table} USING hnsw (embedding vector_cosine_ops)"
                    )
                )
            elif VECTOR_INDEX_METHOD == "ivfflat":
                row_count = _table_row_count(conn, table)
                lists = max(1, min(1000, round(math.sqrt(max(row_count, 1)))))
                conn.execute(
                    text(
                        f"CREATE INDEX IF NOT EXISTS {index_name} "
                        f"ON {table} USING ivfflat (embedding vector_cosine_ops) "
                        f"WITH (lists = {lists})"
                    )
                )
            else:
                raise ValueError(
                    f"Unknown VECTOR_INDEX_METHOD: {VECTOR_INDEX_METHOD!r} "
                    "(expected 'hnsw', 'ivfflat', or 'none')"
                )
        conn.commit()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
